//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Borrower_Details
    {
        public int Borrower_Id { get; set; }

        [DisplayName("Book Name")]

        public Nullable<int> Book_Id { get; set; }

        [DisplayName("Borrow From ")]

        public Nullable<System.DateTime> Borrower_From { get; set; }

        [DisplayName("Borrow To")]

        public Nullable<System.DateTime> Borrower_To { get; set; }

        [DisplayName("Issue By")]

        public Nullable<int> Issue_By { get; set; }
        [DisplayName("Book Name")]

        public virtual Book Book { get; set; }

        [DisplayName("Staff Name")]

        public virtual Staff Staff { get; set; }
    }
}
