//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Member_Details
    {
        public int Member_Id { get; set; }

        [DisplayName("First Name")]
        public string First_Name { get; set; }
        [DisplayName("Last Name")]
        public string Last_Name { get; set; }
        [DisplayName("Phone No")]
        public Nullable<int> Phone_No { get; set; }
        [DisplayName("Email")]
        public string Email { get; set; }
        [DisplayName("User Name")]
        public Nullable<long> User_No { get; set; }
        [DisplayName("Password")]
        public string Pass { get; set; }
        [DisplayName("Role Name")]
        public Nullable<int> Role_Id { get; set; }
        [DisplayName("Role Name")]

        public virtual Role Role { get; set; }
    }
}
